// The IPC method names exposed on window.api. Used by the main process (to
// register handlers), the preload (to build the bridge), and the renderer
// (typed via the Api interface). Must match the exported handler names.
export const API_CHANNELS = [
  "listDirectory",
  "recentRepos",
  "openRepo",
  "cloneRepo",
  "closeRepo",
  "workspace",
  "commitDetail",
  "commitFileDiff",
  "workingFileDiff",
  "fileHunkDiffs",
  "conflictVersions",
  "blameFile",
  "rebaseCommits",
  "gitFetch",
  "gitPush",
  "gitPushSetUpstream",
  "gitPushForce",
  "gitPull",
  "stageFile",
  "stageAll",
  "unstageFile",
  "unstageAll",
  "discardFile",
  "discardAll",
  "commit",
  "amendCommit",
  "checkoutBranch",
  "checkoutCommit",
  "mergeBranch",
  "deleteBranch",
  "renameBranch",
  "deleteRemoteBranch",
  "createBranch",
  "createBranchAt",
  "createRemoteBranch",
  "publishBranch",
  "cherryPick",
  "revertCommit",
  "resetToCommit",
  "createTagAt",
  "deleteTag",
  "deleteRemoteTag",
  "fetchTags",
  "resolveOurs",
  "resolveTheirs",
  "saveResolution",
  "markResolved",
  "abortMerge",
  "continueMerge",
  "stashPush",
  "stashApply",
  "stashPop",
  "stashDrop",
  "stageHunk",
  "unstageHunk",
  "interactiveRebase",
] as const;

export type ApiChannel = (typeof API_CHANNELS)[number];
